export const storePlatform = [
  { value: "Shopify", label: "Shopify" },
  { value: "Cart Functionality", label: "Cart Functionality" },
  { value: "WooCommerce", label: "WooCommerce" },
  { value: "Magento", label: "Magento" },
  { value: "Salesforce Commerce Cloud", label: "Salesforce Commerce Cloud" },
  { value: "PrestaShop", label: "PrestaShop" },
  { value: "VTEX", label: "VTEX" },
  { value: "IBM WebShere Commerce", label: "IBM WebShere Commerce" },
  { value: "Bigcommerce", label: "Bigcommerce" },
  { value: "SAP Commerce Cloud", label: "SAP Commerce Cloud" },
  { value: "Shopware", label: "Shopware" },
  { value: "OpenCart", label: "OpenCart" },
  { value: "nopCommerce", label: "nopCommerce" },
  { value: "Kajabi", label: "Kajabi" },
  { value: "Oracle Commerce", label: "Oracle Commerce" },
  { value: "Shoptet", label: "Shoptet" },
  { value: "Intershop", label: "Intershop" },
  { value: "Oracle Commerce Cloud", label: "Oracle Commerce Cloud" },
  { value: "Loja Integrade", label: "Loja Integrade" },
  { value: "Hybris", label: "Hybris" },
  { value: "Riskified", label: "Riskified" },
  { value: "Zen Cart", label: "Zen Cart" },
  { value: "Nuvemshop", label: "Nuvemshop" },
  { value: "Lightspeed eCom", label: "Lightspeed eCom" },
  { value: "OXID eShop", label: "OXID eShop" },
  { value: "CloudCart", label: "CloudCart" },
  { value: "EPages", label: "EPages" },
  { value: "91App", label: "91App" },
  { value: "Ticimax", label: "Ticimax" },
  { value: "Irroba", label: "Irroba" },
  { value: "X-Cart", label: "X-Cart" },
  { value: "Commerce Server", label: "Commerce Server" },
  { value: "osCommerce", label: "osCommerce" },
  { value: "Drupal Commerce", label: "Drupal Commerce" },
  { value: "Ecwid", label: "Ecwid" },
  { value: "Craft Commerce", label: "Craft Commerce" },
];

export const InvoiceSortingModalDays = [
  "today",
  "yesterday",
  "last 7 days",
  "last 30 days",
  "last 90 days",
  "last 365 days",
  "last month",
  "last 12 months",
  "last year",
];
